package tlb

import (
	"bytes"
	"fmt"
	"math/big"
	"testing"

	"github.com/xssnick/tonutils-go/tvm/cell"
)

func dispatchQueueAccount(t *testing.T, balance *CurrencyCollection, lts ...uint64) AccountDispatchQueue {
	t.Helper()
	messages := cell.NewDict(64)
	for _, lt := range lts {
		msg, err := (EnqueuedMsg{EnqueuedLT: lt, Msg: cell.BeginCell().MustStoreUInt(0xab, 8).EndCell()}).ToCell()
		if err != nil {
			t.Fatal(err)
		}
		if err = messages.SetIntKey(new(big.Int).SetUint64(lt), msg); err != nil {
			t.Fatal(err)
		}
	}
	return AccountDispatchQueue{Messages: messages, Count: uint64(len(lts)), TotalBalance: balance}
}

func TestAccountDispatchQueueBalanceConstructors(t *testing.T) {
	zero := CurrencyCollection{}
	balance := ccFromNano(12345, mustExtraDict(t, map[uint32]int64{7: 17, 42: 93}))
	for _, tc := range []struct {
		name    string
		balance *CurrencyCollection
	}{
		{"old", nil},
		{"new_zero", &zero},
		{"new_extra_currencies", &balance},
	} {
		t.Run(tc.name, func(t *testing.T) {
			queue := dispatchQueueAccount(t, tc.balance, 1<<63+10, 1<<63+20)
			encoded, err := queue.ToCell()
			if err != nil {
				t.Fatal(err)
			}

			want := cell.BeginCell()
			if tc.balance == nil {
				want.MustStoreUInt(1, 1)
			} else {
				want.MustStoreUInt(0, 3)
			}
			want.MustStoreRef(queue.Messages.AsCell()).MustStoreUInt(2, 48)
			if tc.balance != nil {
				want.MustStoreBigCoins(tc.balance.Coins.Nano()).MustStoreDict(tc.balance.ExtraCurrencies)
			}
			mustCellHashEqual(t, "account dispatch wire constructor", encoded, want.EndCell())

			// Reusing a populated receiver must clear the balance on the old tag.
			parsed := AccountDispatchQueue{TotalBalance: &balance}
			loader := encoded.MustBeginParse()
			if err = parsed.LoadFromCell(loader); err != nil {
				t.Fatal(err)
			}
			if loader.BitsLeft() != 0 || loader.RefsNum() != 0 || parsed.Count != queue.Count ||
				!bytes.Equal(parsed.Messages.AsCell().Hash(), queue.Messages.AsCell().Hash()) {
				t.Fatal("account dispatch fields did not round-trip")
			}
			if (parsed.TotalBalance == nil) != (tc.balance == nil) ||
				(tc.balance != nil && !parsed.TotalBalance.Equals(*tc.balance)) {
				t.Fatal("account dispatch balance or constructor changed")
			}
			back, err := parsed.ToCell()
			if err != nil {
				t.Fatal(err)
			}
			mustCellHashEqual(t, "account dispatch round-trip", back, encoded)
		})
	}
}

func TestDispatchQueueAugDataConstructors(t *testing.T) {
	zero := CurrencyCollection{}
	balance := ccFromNano(321, mustExtraDict(t, map[uint32]int64{1: 100}))
	for _, tc := range []struct {
		name    string
		lt      uint64
		balance *CurrencyCollection
	}{
		{"old_max_lt", 1<<63 - 1, nil},
		{"new_zero", 1 << 63, &zero},
		{"new_max_lt_extra_currencies", ^uint64(0), &balance},
	} {
		t.Run(tc.name, func(t *testing.T) {
			extra := DispatchQueueAugData{MinCreatedLT: tc.lt, TotalBalance: tc.balance}
			encoded, err := extra.ToCell()
			if err != nil {
				t.Fatal(err)
			}
			var parsed DispatchQueueAugData
			loader := encoded.MustBeginParse()
			if err = parsed.LoadFromCell(loader); err != nil {
				t.Fatal(err)
			}
			if loader.BitsLeft() != 0 || loader.RefsNum() != 0 || parsed.MinCreatedLT != tc.lt ||
				(parsed.TotalBalance == nil) != (tc.balance == nil) ||
				(tc.balance != nil && !parsed.TotalBalance.Equals(*tc.balance)) {
				t.Fatal("dispatch augmentation fields did not round-trip")
			}
			back, err := parsed.ToCell()
			if err != nil {
				t.Fatal(err)
			}
			mustCellHashEqual(t, "dispatch augmentation round-trip", back, encoded)

			// A leaf can place its own bits and references after the extra. The
			// optional balance dictionary must consume precisely its one ref.
			marker := cell.BeginCell().MustStoreUInt(0xad, 8).EndCell()
			withValue := cell.BeginCell().MustStoreBuilder(encoded.ToBuilder()).
				MustStoreUInt(0xbeef, 16).MustStoreRef(marker).EndCell().MustBeginParse()
			if err = (AugDispatchQueue{}).SkipExtra(withValue); err != nil {
				t.Fatal(err)
			}
			if withValue.MustLoadUInt(16) != 0xbeef ||
				!bytes.Equal(withValue.MustLoadRef().MustToCell().Hash(), marker.Hash()) ||
				withValue.BitsLeft() != 0 || withValue.RefsNum() != 0 {
				t.Fatal("dispatch augmentation consumed part of the leaf value")
			}
		})
	}
	if _, err := (DispatchQueueAugData{MinCreatedLT: 1 << 63}).ToCell(); err == nil {
		t.Fatal("old dispatch augmentation accepted a uint64 lt above uint63")
	}
}

func TestDispatchQueueBalancesAcrossMixedForks(t *testing.T) {
	// Generated by testdata/dispatch-queue/reference.cpp using TON testnet
	// 2fc0ce583a4e9a1d4c6ab9731672cc5d8d6d590d. These are cell hashes, so the
	// fixtures verify constructor bits, balance references and fork extras.
	accountHashes := map[int64]string{
		0: "beecd307de680549b09b963290f1fe2c20dc146b0c8834f61adf3602772e52ed",
		1: "e58aafc00f3c11cf5e1c3b7e1ff0bc37fc22fa4415c0d65adc5fb8144867dfd9",
		2: "5a72807b1b7007a5667c005e09985ae77511059a0a4219427d5dc0f725895b7a",
	}
	a := ccFromNano(100, mustExtraDict(t, map[uint32]int64{1: 10, 2: 20}))
	b := ccFromNano(200, mustExtraDict(t, map[uint32]int64{2: 5, 3: 7}))
	queue, err := NewDispatchQueueAugDict()
	if err != nil {
		t.Fatal(err)
	}
	setAccount := func(key int64, balance *CurrencyCollection, lts ...uint64) {
		t.Helper()
		value, err := dispatchQueueAccount(t, balance, lts...).ToCell()
		if err != nil {
			t.Fatal(err)
		}
		if got := fmt.Sprintf("%x", value.Hash()); got != accountHashes[key] {
			t.Fatalf("account %d hash = %s, want C++ %s", key, got, accountHashes[key])
		}
		if err = queue.SetIntKey(big.NewInt(key), value); err != nil {
			t.Fatal(err)
		}
	}
	checkRoot := func(lt uint64, balance *CurrencyCollection, wantHash string) {
		t.Helper()
		var root DispatchQueueAugData
		if err := root.LoadFromCell(queue.GetRootExtra().MustBeginParse()); err != nil {
			t.Fatal(err)
		}
		if root.MinCreatedLT != lt || (root.TotalBalance == nil) != (balance == nil) ||
			(balance != nil && !root.TotalBalance.Equals(*balance)) {
			t.Fatalf("root augmentation = %+v, want lt %d and balance %+v", root, lt, balance)
		}
		encoded, err := queue.ToCell()
		if err != nil {
			t.Fatal(err)
		}
		if got := fmt.Sprintf("%x", encoded.Hash()); got != wantHash {
			t.Fatalf("dispatch queue hash = %s, want C++ %s", got, wantHash)
		}
		var parsed DispatchQueueAugDict
		if err = parsed.LoadFromCell(encoded.MustBeginParse()); err != nil {
			t.Fatal(err)
		}
		if !parsed.ValidateAll() {
			t.Fatal("valid dispatch queue failed augmentation validation")
		}
		back, err := parsed.ToCell()
		if err != nil {
			t.Fatal(err)
		}
		mustCellHashEqual(t, "mixed dispatch queue round-trip", back, encoded)
	}

	setAccount(1, &a, 800, 850)
	checkRoot(800, &a, "05403617d97bd6013a80a155e1e7c2ea1ed14ec4f875748b8911df4253c6f1a7")
	setAccount(2, &b, 900)
	sum := ccFromNano(300, mustExtraDict(t, map[uint32]int64{1: 10, 2: 25, 3: 7}))
	checkRoot(800, &sum, "26fe045810193a26afa90e71677d5837903f144def9c5f52a82ec32ac405df16")
	setAccount(0, nil, 700)
	checkRoot(700, nil, "995ce670d4888ea83173ea2a4349b4181f108a6096d06fb3fcca6560d421fc4e")
	if err = queue.DeleteIntKey(big.NewInt(0)); err != nil {
		t.Fatal(err)
	}
	checkRoot(800, &sum, "26fe045810193a26afa90e71677d5837903f144def9c5f52a82ec32ac405df16")
	if err = queue.DeleteIntKey(big.NewInt(1)); err != nil {
		t.Fatal(err)
	}
	checkRoot(900, &b, "0c0712483fc2a3aaf618c675355888b7c736ff120c34634710d2329b784c6d3f")
	if err = queue.DeleteIntKey(big.NewInt(2)); err != nil {
		t.Fatal(err)
	}
	checkRoot(0, nil, "f733e03b9a817e95b750f9526ea9666114f4e9d99e976571532adff29f131807")

	if extraAmount(t, a.ExtraCurrencies, 2).Int64() != 20 || extraAmount(t, b.ExtraCurrencies, 2).Int64() != 5 {
		t.Fatal("fork balance addition mutated an account's balance")
	}
}

func TestDispatchQueueValidationRejectsIncorrectLeafBalance(t *testing.T) {
	balance := ccFromNano(100, mustExtraDict(t, map[uint32]int64{7: 30}))
	account, err := dispatchQueueAccount(t, &balance, 123).ToCell()
	if err != nil {
		t.Fatal(err)
	}
	incorrect := ccFromNano(99, balance.ExtraCurrencies)
	for _, totalBalance := range []*CurrencyCollection{nil, &incorrect} {
		forged, err := (DispatchQueueAugData{MinCreatedLT: 123, TotalBalance: totalBalance}).ToCell()
		if err != nil {
			t.Fatal(err)
		}
		// A one-account dictionary with sender key zero uses hml_same$11,
		// followed by the leaf's extra and the account queue value.
		root := cell.BeginCell().MustStoreUInt(0b11, 2).MustStoreBoolBit(false).
			MustStoreUInt(256, 9).MustStoreBuilder(forged.ToBuilder()).
			MustStoreBuilder(account.ToBuilder()).EndCell()
		encoded := cell.BeginCell().MustStoreBoolBit(true).MustStoreRef(root).
			MustStoreBuilder(forged.ToBuilder()).EndCell()
		var parsed DispatchQueueAugDict
		if err = parsed.LoadFromCell(encoded.MustBeginParse()); err != nil {
			t.Fatal(err)
		}
		if parsed.ValidateAll() {
			t.Fatal("dispatch dictionary accepted a leaf balance that differs from its account")
		}
	}
}

func TestDispatchQueueRejectsInvalidConstructors(t *testing.T) {
	account := dispatchQueueAccount(t, nil, 123)
	for _, tc := range []struct {
		name  string
		value *cell.Cell
	}{
		{"reserved_001", cell.BeginCell().MustStoreUInt(1, 3).MustStoreRef(account.Messages.AsCell()).MustStoreUInt(1, 48).EndCell()},
		{"reserved_01", cell.BeginCell().MustStoreUInt(1, 2).MustStoreRef(account.Messages.AsCell()).MustStoreUInt(1, 48).EndCell()},
		{"old_without_count", cell.BeginCell().MustStoreUInt(1, 1).MustStoreRef(account.Messages.AsCell()).EndCell()},
		{"new_without_balance", cell.BeginCell().MustStoreUInt(0, 3).MustStoreRef(account.Messages.AsCell()).MustStoreUInt(1, 48).EndCell()},
		{"new_missing_currency_ref", cell.BeginCell().MustStoreUInt(0, 3).MustStoreRef(account.Messages.AsCell()).MustStoreUInt(1, 48).MustStoreUInt(1, 5).EndCell()},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var parsed AccountDispatchQueue
			if err := parsed.LoadFromCell(tc.value.MustBeginParse()); err == nil {
				t.Fatal("invalid account dispatch constructor was accepted")
			}
			if _, err := buildAugmentationLeafExtra(AugDispatchQueue{}, tc.value.MustBeginParse()); err == nil {
				t.Fatal("invalid account dispatch constructor produced a leaf extra")
			}
		})
	}
	for _, value := range []*cell.Cell{
		cell.BeginCell().MustStoreUInt(0b11, 2).MustStoreUInt(0, 64).EndCell(),
		cell.BeginCell().MustStoreUInt(0b10, 2).MustStoreUInt(0, 64).EndCell(),
		cell.BeginCell().MustStoreUInt(0, 63).EndCell(),
	} {
		var parsed DispatchQueueAugData
		if err := parsed.LoadFromCell(value.MustBeginParse()); err == nil {
			t.Fatal("invalid dispatch augmentation was accepted")
		}
		if err := (AugDispatchQueue{}).SkipExtra(value.MustBeginParse()); err == nil {
			t.Fatal("invalid dispatch augmentation was skipped")
		}
	}
}

func TestDispatchQueueBalanceOverflowPreservesDictionary(t *testing.T) {
	max := new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 120), big.NewInt(1))
	a := CurrencyCollection{Coins: FromNanoTON(max)}
	b := ccFromNano(1, nil)
	queue, err := NewDispatchQueueAugDict()
	if err != nil {
		t.Fatal(err)
	}
	first, err := dispatchQueueAccount(t, &a, 100).ToCell()
	if err != nil {
		t.Fatal(err)
	}
	if err = queue.SetIntKey(big.NewInt(1), first); err != nil {
		t.Fatal(err)
	}
	before, err := queue.ToCell()
	if err != nil {
		t.Fatal(err)
	}
	second, err := dispatchQueueAccount(t, &b, 200).ToCell()
	if err != nil {
		t.Fatal(err)
	}
	if err = queue.SetIntKey(big.NewInt(2), second); err == nil {
		t.Fatal("dispatch fork accepted a balance above Grams capacity")
	}
	after, err := queue.ToCell()
	if err != nil {
		t.Fatal(err)
	}
	mustCellHashEqual(t, "dispatch queue after rejected balance overflow", after, before)
}

func TestDispatchQueueMinLTConstructorBoundary(t *testing.T) {
	queue, err := NewDispatchQueueAugDict()
	if err != nil {
		t.Fatal(err)
	}
	oldHighLT, err := dispatchQueueAccount(t, nil, 1<<63+10).ToCell()
	if err != nil {
		t.Fatal(err)
	}
	if err = queue.SetIntKey(big.NewInt(1), oldHighLT); err == nil {
		t.Fatal("old account produced a dispatch augmentation above uint63")
	}
	if !queue.IsEmpty() || queue.GetRootExtra().MustBeginParse().MustLoadUInt(64) != 0 {
		t.Fatal("rejected lt overflow changed the empty dispatch queue")
	}
	zero := CurrencyCollection{}
	newHighLT, err := dispatchQueueAccount(t, &zero, 1<<63+10).ToCell()
	if err != nil {
		t.Fatal(err)
	}
	if err = queue.SetIntKey(big.NewInt(1), newHighLT); err != nil {
		t.Fatal(err)
	}
	var extra DispatchQueueAugData
	if err = extra.LoadFromCell(queue.GetRootExtra().MustBeginParse()); err != nil {
		t.Fatal(err)
	}
	if extra.MinCreatedLT != 1<<63+10 || extra.TotalBalance == nil || !extra.TotalBalance.Equals(zero) {
		t.Fatalf("high lt new augmentation = %+v", extra)
	}
	oldLowLT, err := dispatchQueueAccount(t, nil, 10).ToCell()
	if err != nil {
		t.Fatal(err)
	}
	if err = queue.SetIntKey(big.NewInt(0), oldLowLT); err != nil {
		t.Fatal(err)
	}
	if err = extra.LoadFromCell(queue.GetRootExtra().MustBeginParse()); err != nil {
		t.Fatal(err)
	}
	if extra.MinCreatedLT != 10 || extra.TotalBalance != nil {
		t.Fatalf("mixed high/low lt augmentation = %+v", extra)
	}
	if err = queue.DeleteIntKey(big.NewInt(0)); err != nil {
		t.Fatal(err)
	}
	if err = extra.LoadFromCell(queue.GetRootExtra().MustBeginParse()); err != nil {
		t.Fatal(err)
	}
	if extra.MinCreatedLT != 1<<63+10 || extra.TotalBalance == nil {
		t.Fatal("removing old account did not restore the new high lt augmentation")
	}
}
